### ISSUE TITLE
Parser error with arithmetic sorts

### ISSUE THREAD

**Issue by rodrigo7491** [ufmg-smite/carcara#7]
Hi,

When trying to check the proof produced by cvc5 for the files in [ex.zip](https://github.com/ufmg-smite/carcara/files/11374717/ex.zip), I get the following error:

```
[ERROR] parser error: sort error: expected 'Real', got 'Int' (on line 27, column 48)
invalid
```

I'm running cvc5 v1.0.5 and carcara v1.0.0, CLI commands below. 

`cvc5 --produce-proofs --proof-format=alethe --proof-granularity=theory-rewrite --flatten-ho-chains file.smt2`
`carcara check file.proof file.smt2`

**Comment by bpandreotti** [comment]
Hi!

This error is happening because cvc5 considers `Int` a subtype of `Real`, while Carcara (by default) does not. If you pass the flag `--allow-int-real-subtyping` to Carcara, it should fix it (you probably will also have to pass `--skip-unknown-rules`).

Also, thanks for letting me know about the `--ignore-unknown-rules` thing! I'll fix it right away.

**Comment by rodrigo7491** [comment]
Using `--allow-int-real-subtyping` fixes the problem, thanks!
