### ISSUE TITLE
Checking failed with rule 'resolution': pivot was not eliminated

### ISSUE THREAD

**Issue by rodrigo7491** [ufmg-smite/carcara#9]
Hi,

When trying to check the proof produced by cvc5 for the files in [ex.zip](https://github.com/ufmg-smite/carcara/files/11495796/ex.zip), I get the following error:

```
[ERROR] checking failed on step 't7599' with rule 'resolution': pivot was not eliminated: '(not (or (not (>= E 1)) (not (and (>= E 0) (not (>= E 1))))))'
invalid
```

Checking the proof with carcara repeatedly yields different error messages, all mentioning step `t7599`. Two other error messages are below.

```
[ERROR] checking failed on step 't7599' with rule 'resolution': pivot was not eliminated: '(not (and (>= E 0) (not (>= E 1))))'
invalid
```
```
[ERROR] checking failed on step 't7599' with rule 'resolution': pivot was not eliminated: '(not (>= E 1))'
invalid
```

Unfortunately I was not able to reproduce the error with a smaller instance. I'm running cvc5 v1.0.5 and carcara v1.0.0, CLI commands below.

`cvc5 --produce-proofs --proof-format=alethe --proof-granularity=theory-rewrite --flatten-ho-chains ex.smt2`
`carcara check --skip-unknown-rules --allow-int-real-subtyping ex.proof ex.smt2`

**Comment by bpandreotti** [comment]
After a lot of investigation, I am convinced that this is a bug in cvc5, and not in Carcara.

The proof fails on the `t7599` step, which uses the resolution rule. Two of its premises are:
```
(step t7557 (cl (not (>= E 1)) (not (and (>= E 0) (not (>= E 1))))) :rule ...)
(step t7586 (cl (>= E 0) (not (and (>= E 0) (not (>= E 1))))) :rule ...)
```

If these steps, instead of concluding a clause of two terms, concluded a unit clause with an `or` term (like applying the inverse of the `or` rule), the proof would be valid:
```
(step t7557 (cl (or (not (>= E 1)) (not (and (>= E 0) (not (>= E 1)))))) :rule ...)
(step t7586 (cl (or (>= E 0) (not (and (>= E 0) (not (>= E 1)))))) :rule ...)
```

(the negations of these two `or` terms are introduced in `t7599`'s first premise, `t1035`)
